// dshot_diag.rs — DShot peripheral-state instrumentation.
//
// All four motors are still failing to decode on hardware (2026-04-22
// session, see docs/motor-bringup-log.md). DTCM-buffer hypothesis was
// disproved 2026-04-25: relocating to SRAM2 didn't change behaviour.
// We were debugging the loudest peripheral on the board with zero
// driver-level instrumentation, so this module fills that gap until
// the oscilloscope arrives.
//
// Two entry points:
//   - log_boot_state(): one-shot dump of caches, all three timers'
//     full PWM/DMA register state, and a write-then-readback canary
//     on the SRAM2 DMA buffers. Run once after DshotQuad::new.
//   - log_runtime_state(): post-transfer DMA stream state + the last
//     CCR value the timer holds. Cheap; call ~1 Hz.
//
// Anything surprising here narrows the root cause before scope work.

use embassy_stm32::pac;

/// Build identifier, logged at DShot init so a bench log can be tied to the
/// source that produced it. Generated by `build.rs` as `<epoch>-<sha>[-dirty]`
/// and echoed by the flash scripts — if the log doesn't match what you just
/// flashed, you're looking at stale firmware and the trace means nothing.
pub const BUILD_TAG: &str = env!("FC_BUILD_STAMP");

/// Live pad level of PA0..PA3 (M1..M4), one bit per motor, PA0 = bit 0.
/// IDR reads the actual pin, whatever drives it — timer AF, GPIO output,
/// or an external pull — so this is ground truth for "what is the wire
/// doing right now".
pub fn read_pa_low() -> u8 {
    (pac::GPIOA.idr().read().0 & 0xF) as u8
}

/// Self-test for the bidir RX path: generate edges on PA0/M1 ourselves,
/// while the channel is in input-capture mode with the RX DMA armed.
///
/// `NoEdge` on every frame is ambiguous — it looks the same whether the ESC
/// is silent or our capture chain (CCMR input mode, CCxNP both-edges, the
/// P2M DMA reprogram) never worked in the first place. Driving the pad from
/// the FC side removes the ESC from the experiment: if these pulses come
/// back as captured edges, the receive path is functional and the silence is
/// the ESC's; if they don't, the bug is on our side and no amount of
/// waveform tuning on the TX side will ever produce telemetry.
///
/// Emits 4 low pulses of ~2 µs at ~4 µs spacing = 8 edges, comfortably over
/// `MIN_GCR_EDGES`. Leaves the pad HIGH and back on AF. Perturbs one frame.
pub fn rx_loopback_pulse_pa0() {
    use pac::gpio::vals::Moder;

    // ODR bit 0 is already 1 (the glitch guard leaves it set), so switching
    // to OUTPUT starts from idle-high and the pad never dips on entry.
    pac::GPIOA.moder().modify(|w| w.set_moder(0, Moder::OUTPUT));
    for _ in 0..4 {
        pac::GPIOA.bsrr().write(|w| w.set_br(0, true));
        cortex_m::asm::delay(960); // ~2 µs at 480 MHz
        pac::GPIOA.bsrr().write(|w| w.set_bs(0, true));
        cortex_m::asm::delay(960);
    }
    pac::GPIOA.moder().modify(|w| w.set_moder(0, Moder::ALTERNATE));
}

/// Report what the RX self-test actually captured.
///
/// Call while the channels are still in input-capture mode, so the CCMR dump
/// reflects the receive configuration rather than the TX one.
///
/// The timestamps are the discriminator. The self-test drives edges 2 µs
/// apart and the capture counter runs at 12 MHz, so consecutive captures are
/// ~24 ticks apart. Gaps of ~96 ticks mean `ICxPSC` is dividing by 4; a short
/// run of ~24-tick gaps that then stops means captures are being lost for
/// some other reason (buffer, DMA, overcapture).
pub fn log_rx_loopback_result(edges: [u32; 4], m1_buf: &[u32]) {
    let ccmr1 = pac::TIM2.ccmr_input(0).read();
    let ccmr2 = pac::TIM2.ccmr_input(1).read();

    defmt::info!(
        "RX loopback self-test [{=str}]: 8 edges driven on PA0/M1 -> captured M1={=u32} M2={=u32} M3={=u32} M4={=u32}",
        BUILD_TAG,
        edges[0], edges[1], edges[2], edges[3],
    );
    defmt::info!(
        "  input-mode CCMR1=0x{=u32:08x} CCMR2=0x{=u32:08x} CCER=0x{=u32:08x} | ch1: CCS={=u8} ICPSC={=u8} ICF={=u8}  (want CCS=1 ICPSC=0)",
        ccmr1.0 as u32,
        ccmr2.0 as u32,
        pac::TIM2.ccer().read().0 as u32,
        ccmr1.ccs(0).to_bits(),
        ccmr1.icpsc(0),
        ccmr1.icf(0).to_bits(),
    );
    defmt::info!(
        "  M1 capture words[0..8]: {=u32} {=u32} {=u32} {=u32} {=u32} {=u32} {=u32} {=u32}",
        m1_buf[0], m1_buf[1], m1_buf[2], m1_buf[3],
        m1_buf[4], m1_buf[5], m1_buf[6], m1_buf[7],
    );
    // Gap between the first two captures, in 12 MHz ticks: ~24 = every edge,
    // ~96 = every 4th edge.
    if edges[0] >= 2 {
        defmt::info!(
            "  first inter-capture gap = {=u32} ticks (24 = every edge, 96 = ICxPSC div4)",
            m1_buf[1].wrapping_sub(m1_buf[0]),
        );
    }
    match edges[0] {
        0 => defmt::error!(
            "  M1 captured NOTHING from a self-driven edge — the receive path is broken, not the ESC"
        ),
        8 => defmt::info!("  M1 captured all 8 — receive path is sound"),
        n => defmt::error!(
            "  M1 captured {=u32} of 8 — the receive path is LOSING edges; a 21-edge GCR reply would land under MIN_GCR_EDGES and report NoEdge regardless of what the ESC sends",
            n
        ),
    }
}

/// Pad level through the transmit setup, sampled on one frame.
///
/// The idle probe shows the pad HIGH when the direction switch finishes, yet
/// the frame begins with ~2 cells of stuck-LOW. Since the switch now runs
/// immediately before transmit, whatever asserts the line does so inside the
/// handful of statements between them. These five samples bracket each one,
/// so the culprit is whichever step the level drops at rather than something
/// to be deduced from the reference manual.
///
/// Reads are single register accesses, so the trace costs nanoseconds and
/// does not shift the timing it is measuring. Logged after the frame has
/// gone out, for the same reason.
pub fn log_tx_setup_trace(idr: [u8; 5]) {
    defmt::info!(
        "TX setup trace [{=str}] PA0..3: after switch={=u8:04b} | after ARR/CNT={=u8:04b} | after CCxDE={=u8:04b} | after DMA armed={=u8:04b} | after frame={=u8:04b}",
        BUILD_TAG,
        idr[0], idr[1], idr[2], idr[3], idr[4],
    );
    let names = [
        "already low when the switch returned (contradicts the idle probe)",
        "the ARR/CNT/ARPE writes",
        "enabling CCxDE",
        "arming the DMA streams",
    ];
    for (i, name) in names.iter().enumerate() {
        if idr[i] & 1 == 0 {
            defmt::error!("  M1 first goes LOW at: {=str}", *name);
            return;
        }
    }
    defmt::info!("  M1 stayed HIGH through the whole setup — the stuck LOW starts inside the frame itself");
}

/// One-shot probe of the bidir RX→TX direction switch.
///
/// The scope shows ~8 µs of LOW on M1 between the telemetry window and the
/// next frame, where bidir idle should be HIGH. That is either the OC output
/// stuck in its active state, or the pin not being driven by the OC at all.
/// This walks the candidate releases in order and reports the pad level
/// after each, which distinguishes them in a single flash:
///
///   A releases it → the preload path was the problem
///   B releases it → the active register held a stale capture value
///   C releases it → it's the compare condition, not the register value
///   D flips it    → we do control the pin (sanity check)
///   nothing moves → the OC isn't driving the pad; look at MODER/AFR/CCxE
///
/// Pokes PA0/M1 only; PA1..3 are read for context. Perturbs one frame, so
/// call it from the ESC-arming window while the motors are stopped.
pub fn probe_output_idle(idr_during_rx: u8) {
    use pac::timer::vals::Ocm;
    let t = pac::TIM2;
    // ~5 µs at 480 MHz: longer than the 12 MHz timer tick, so the pad has
    // settled before each read.
    fn settle() {
        cortex_m::asm::delay(2400);
    }

    defmt::info!("=== bidir idle probe [{=str}] ===", BUILD_TAG);
    defmt::info!(
        "PA0..3 IDR: during RX (input+pullup) = {=u8:04b} | after switch to OC = {=u8:04b}  (bidir idle wants 1111)",
        idr_during_rx,
        read_pa_low(),
    );
    defmt::info!(
        "TIM2 after switch: CCER={=u32:08x} CCMR1={=u32:08x} CCMR2={=u32:08x} CNT={=u32} ARR={=u32} CCR(read)={=u32}/{=u32}/{=u32}/{=u32}",
        t.ccer().read().0 as u32,
        t.ccmr_output(0).read().0 as u32,
        t.ccmr_output(1).read().0 as u32,
        t.cnt().read(),
        t.arr().read(),
        t.ccr(0).read(),
        t.ccr(1).read(),
        t.ccr(2).read(),
        t.ccr(3).read(),
    );

    // A: clear via the preload path + forced update (the original guard).
    t.ccmr_output(0).modify(|w| w.set_ocpe(0, true));
    t.ccr(0).write_value(0);
    t.egr().write(|w| w.set_ug(true));
    settle();
    defmt::info!("A: CCR1=0 via preload + UG  -> IDR={=u8:04b}", read_pa_low());

    // B: clear straight into the active register.
    t.ccmr_output(0).modify(|w| w.set_ocpe(0, false));
    t.ccr(0).write_value(0);
    settle();
    defmt::info!("B: CCR1=0 write-through     -> IDR={=u8:04b}", read_pa_low());

    // C: bypass the comparator entirely — OCxREF forced inactive, which
    //    with CCxP=1 (bidir) should drive the pad HIGH.
    t.ccmr_output(0).modify(|w| w.set_ocm(0, Ocm::FORCE_INACTIVE));
    settle();
    defmt::info!("C: OCM=FORCE_INACTIVE       -> IDR={=u8:04b}  (want PA0=1)", read_pa_low());

    // D: sanity — forcing active must drive it the other way. If C and D
    //    read the same, the timer isn't reaching the pad at all.
    t.ccmr_output(0).modify(|w| w.set_ocm(0, Ocm::FORCE_ACTIVE));
    settle();
    defmt::info!("D: OCM=FORCE_ACTIVE         -> IDR={=u8:04b}  (want PA0=0)", read_pa_low());

    // Restore the normal TX configuration.
    t.ccmr_output(0).modify(|w| {
        w.set_ocm(0, Ocm::PWM_MODE1);
        w.set_ocpe(0, true);
    });
    t.ccr(0).write_value(0);
    t.egr().write(|w| w.set_ug(true));
    settle();
    defmt::info!("E: restored PWM1 + preload  -> IDR={=u8:04b}", read_pa_low());
}

/// RCC TIMPRE bit. F7-specific: when 0 the timer clock is APBx*2
/// (when APB prescaler > 1); when 1 it's APBx*4. With our APB1
/// prescaler of /4, TIMPRE=1 doubles the timer clock to 216 MHz —
/// our PSC=0/ARR=179 would then produce DShot1200 timing, which
/// BLHeli_S can't decode (max DShot600).
pub fn log_timpre() {
    use pac::rcc::vals::Timpre;
    let t = pac::RCC.cfgr().read().timpre();
    let raw = t.to_bits();
    let label: &str = match t {
        Timpre::DEFAULT_X2 => "DEFAULT_X2 (timer = APB*2 = 240 MHz expected)",
        Timpre::DEFAULT_X4 => "DEFAULT_X4 (timer = HCLK = 480 MHz)",
    };
    defmt::info!("RCC.CFGR.TIMPRE = {=u8} ({=str})", raw, label);
    if !matches!(t, Timpre::DEFAULT_X2) {
        defmt::error!("TIMPRE != DEFAULT_X2 — actual bit rate is double what we configured");
    }
}

/// Dump GPIO MODER/OSPEEDR/AFR for the four DShot pins. If any pin
/// isn't in AF mode at the right AF number with VeryHigh slew, the
/// signal at the pad won't match what the timer is generating.
pub fn log_gpio_pins() {
    // All four DShot motor pins are on GPIOA: PA0..PA3 = TIM2 CH1..CH4
    // (M1..M4). TIM2 alternate function is AF1 on this part. Pins 0..3
    // all live in AFRL (afr(0)). MODER/OSPEEDR are 2 bits/pin.
    let a = pac::GPIOA;
    let moder = a.moder().read().0;
    let ospd  = a.ospeedr().read().0;
    let pupd  = a.pupdr().read().0;
    let afrl  = a.afr(0).read().0;

    let pin_state = |p: u32| -> (u32, u32, u32, u32) {
        let mode = (moder >> (p * 2)) & 0b11;
        let spd  = (ospd  >> (p * 2)) & 0b11;
        let pu   = (pupd  >> (p * 2)) & 0b11;
        let af   = (afrl  >> (p * 4)) & 0xF;
        (mode, spd, pu, af)
    };

    let (m0, s0, u0, a0) = pin_state(0); // PA0 → TIM2_CH1 → M1
    let (m1, s1, u1, a1) = pin_state(1); // PA1 → TIM2_CH2 → M2
    let (m2, s2, u2, a2) = pin_state(2); // PA2 → TIM2_CH3 → M3
    let (m3, s3, u3, a3) = pin_state(3); // PA3 → TIM2_CH4 → M4

    // Expected: MODER=2 (AF), OSPEEDR=1 (Low, matches BF), PUPDR=1
    // (PullUp for bidir idle-high), AF=1 (TIM2).
    defmt::info!("GPIO PA0 (M1/TIM2_CH1): MODER={=u32} OSPEEDR={=u32} PUPDR={=u32} AF={=u32} (want 2/1/1/1)",
                  m0, s0, u0, a0);
    defmt::info!("GPIO PA1 (M2/TIM2_CH2): MODER={=u32} OSPEEDR={=u32} PUPDR={=u32} AF={=u32} (want 2/1/1/1)",
                  m1, s1, u1, a1);
    defmt::info!("GPIO PA2 (M3/TIM2_CH3): MODER={=u32} OSPEEDR={=u32} PUPDR={=u32} AF={=u32} (want 2/1/1/1)",
                  m2, s2, u2, a2);
    defmt::info!("GPIO PA3 (M4/TIM2_CH4): MODER={=u32} OSPEEDR={=u32} PUPDR={=u32} AF={=u32} (want 2/1/1/1)",
                  m3, s3, u3, a3);
}

/// Read each timer's CNT three times in a row. If CNT is changing,
/// the timer is alive; if stuck, CEN is being cleared somewhere.
pub fn log_timer_running() {
    let a2 = pac::TIM2.cnt().read();
    let b2 = pac::TIM2.cnt().read();
    let c2 = pac::TIM2.cnt().read();
    let a3 = pac::TIM3.cnt().read().cnt();
    let b3 = pac::TIM3.cnt().read().cnt();
    let c3 = pac::TIM3.cnt().read().cnt();
    let a4 = pac::TIM4.cnt().read().cnt();
    let b4 = pac::TIM4.cnt().read().cnt();
    let c4 = pac::TIM4.cnt().read().cnt();
    defmt::info!("TIM2 CNT samples: {=u32} {=u32} {=u32}", a2, b2, c2);
    defmt::info!("TIM3 CNT samples: {=u16} {=u16} {=u16}", a3, b3, c3);
    defmt::info!("TIM4 CNT samples: {=u16} {=u16} {=u16}", a4, b4, c4);
}

/// SCB_CCR cache enable bits — D-cache uncoherent with DMA is a
/// classic F7 footgun, so verify it's off (Embassy default).
pub fn log_caches() {
    let ccr = unsafe { core::ptr::read_volatile(0xE000_ED14 as *const u32) };
    let ic = (ccr >> 17) & 1;
    let dc = (ccr >> 16) & 1;
    defmt::info!("SCB_CCR = {=u32:08x}  IC={=u32}  DC={=u32}", ccr, ic, dc);
    if dc == 1 {
        defmt::warn!("D-cache enabled — DMA buffers need MPU non-cacheable region");
    }
}

/// Dump TIM2 (32-bit) PWM+DMA configuration registers.
pub fn log_tim2_config() {
    let t = pac::TIM2;
    defmt::info!(
        "TIM2: PSC={=u16} ARR={=u32} CR1={=u32:08x} DIER={=u32:08x} DCR={=u32:08x} CCMR1={=u32:08x} CCER={=u32:08x} CCR1={=u32} CCR2={=u32}",
        t.psc().read(),
        t.arr().read(),
        t.cr1().read().0,
        t.dier().read().0,
        t.dcr().read().0,
        t.ccmr_output(0).read().0,
        t.ccer().read().0,
        t.ccr(0).read(),
        t.ccr(1).read(),
    );
}

/// Dump TIM3 (16-bit) PWM+DMA configuration registers.
pub fn log_tim3_config() {
    let t = pac::TIM3;
    defmt::info!(
        "TIM3: PSC={=u16} ARR={=u16} CR1={=u32:08x} DIER={=u32:08x} DCR={=u32:08x} CCMR1={=u32:08x} CCER={=u32:08x} CCR1={=u16}",
        t.psc().read(),
        t.arr().read().arr(),
        t.cr1().read().0,
        t.dier().read().0,
        t.dcr().read().0,
        t.ccmr_output(0).read().0,
        t.ccer().read().0,
        t.ccr(0).read().ccr(),
    );
}

/// Dump TIM4 (16-bit) PWM+DMA configuration registers.
pub fn log_tim4_config() {
    let t = pac::TIM4;
    defmt::info!(
        "TIM4: PSC={=u16} ARR={=u16} CR1={=u32:08x} DIER={=u32:08x} DCR={=u32:08x} CCMR1={=u32:08x} CCER={=u32:08x} CCR1={=u16}",
        t.psc().read(),
        t.arr().read().arr(),
        t.cr1().read().0,
        t.dier().read().0,
        t.dcr().read().0,
        t.ccmr_output(0).read().0,
        t.ccer().read().0,
        t.ccr(0).read().ccr(),
    );
}

/// Decode + log the post-transfer state of a DMA1 stream.
///
/// `name`: "TIM2_UP", "TIM3_UP", "TIM4_UP" etc.
/// `stream`: 0..=7 within DMA1.
pub fn log_dma1_stream(name: &'static str, stream: usize) {
    let dma = pac::DMA1;
    let st = dma.st(stream);
    let cr = st.cr().read().0;
    let ndtr = st.ndtr().read().0 & 0xFFFF;
    let par = st.par().read();
    let m0ar = st.m0ar().read();
    let fcr = st.fcr().read().0;

    // Per-stream flag bits in LISR (streams 0..=3) / HISR (4..=7).
    // Within each stream's 6-bit slot: FE(0) - DME(2) TE(3) HT(4) TC(5).
    let isr_word = dma.isr(if stream < 4 { 0 } else { 1 }).read().0;
    let shift = match stream % 4 {
        0 => 0, 1 => 6, 2 => 16, 3 => 22, _ => 0,
    };
    let bits = (isr_word >> shift) & 0x3F;
    let fe  = (bits & 0x01) != 0;
    let dme = (bits & 0x04) != 0;
    let te  = (bits & 0x08) != 0;
    let ht  = (bits & 0x10) != 0;
    let tc  = (bits & 0x20) != 0;

    defmt::info!(
        "DMA1 S{=usize} {=str}: EN={=bool} NDTR={=u32} PAR={=u32:08x} M0AR={=u32:08x} CR={=u32:08x} FCR={=u32:08x} | TC={=bool} HT={=bool} TE={=bool} DME={=bool} FE={=bool}",
        stream, name,
        (cr & 1) != 0,
        ndtr, par, m0ar, cr, fcr,
        tc, ht, te, dme, fe,
    );
    if te || dme {
        defmt::warn!("DMA1 S{=usize} {=str}: error flags set (TE/DME)", stream, name);
    }
    if fe && !te && !dme {
        // FE (FIFO Error) alone is benign on H7 burst DMA — fires when
        // the FIFO drains at transfer completion. Not a data-integrity issue.
        defmt::trace!("DMA1 S{=usize} {=str}: FE flag (benign)", stream, name);
    }

    // Clear all six flags for this stream so the next 1 Hz log
    // reflects only the past second, not everything since boot.
    let mut ifcr = 0u32;
    ifcr |= 0x3D << shift;  // CTCIF | CHTIF | CTEIF | CDMEIF | CFEIF (bits 5,4,3,2,0)
    pac::DMA1.ifcr(if stream < 4 { 0 } else { 1 }).write_value(
        pac::dma::regs::Ixr(ifcr)
    );
}

/// Write a known pattern into a buffer, read it back, log mismatches.
/// Catches MPU/aliasing/bus issues at the hardcoded SRAM2 addresses.
pub fn canary_check(name: &'static str, buf: &mut [u16]) {
    const PATTERN_A: u16 = 0xA5A5;
    const PATTERN_B: u16 = 0x5A5A;

    for (i, cell) in buf.iter_mut().enumerate() {
        *cell = if i & 1 == 0 { PATTERN_A } else { PATTERN_B };
    }
    // Fence to make sure stores are committed before the readback.
    cortex_m::asm::dsb();

    let mut bad = 0u32;
    for (i, cell) in buf.iter().enumerate() {
        let expect = if i & 1 == 0 { PATTERN_A } else { PATTERN_B };
        if *cell != expect {
            if bad < 4 {
                defmt::warn!(
                    "canary {=str}[{=usize}] = {=u16:04x} (expected {=u16:04x})",
                    name, i, *cell, expect,
                );
            }
            bad += 1;
        }
    }
    if bad == 0 {
        defmt::info!("canary {=str}: ok ({=usize} cells)", name, buf.len());
    } else {
        defmt::error!("canary {=str}: {=u32} mismatches in {=usize} cells",
                       name, bad, buf.len());
    }

    // Restore zeros so first send() starts from a clean buffer.
    buf.fill(0);
    cortex_m::asm::dsb();
}
